import {sql} from 'drizzle-orm';
import type {Config} from '../../config.js';
import type {Db} from '../../db/client.js';
import {audit} from '../../audit.js';
import {classifyScore} from '../../domain.js';
import {legacyVehicleFit,scoreCompany} from '../../qualification/scorer.js';
import type {JobDependencies} from '../dependencies.js';
import {effectiveMode} from '../runtime-config.js';
import {enqueue} from '../queue.js';
import {getSuppressionDecision} from '../../outreach/suppression.js';

export async function qualifyHandler(db:Db,config:Config,job:any,deps:JobDependencies){
  const companyId=String(job.payload.companyId);const company=(await db.execute(sql`SELECT id,name,address,status,domain FROM companies WHERE id=${companyId}`)).rows[0] as any;if(!company)throw new Error('COMPANY_NOT_FOUND');
  const source=(await db.execute(sql`SELECT id FROM sources WHERE company_id=${companyId} LIMIT 1`)).rows[0];const evidence=(await db.execute(sql`SELECT id,excerpt,signal_type,confidence,observed_at FROM evidence WHERE company_id=${companyId}`)).rows as any[];if(!source||!evidence.length){await db.execute(sql`UPDATE companies SET status='DISCARDED',updated_at=now() WHERE id=${companyId} AND status NOT IN ('BLOCKED','STOPPED')`);await audit(db,'QUALIFICATION_REJECTED',{reason:'NO_SOURCE_OR_EVIDENCE'},companyId,job.id);return}
  const suppression=await getSuppressionDecision(db,companyId);if(suppression.suppressed){await audit(db,'QUALIFICATION_REJECTED',{reason:'SUPPRESSED',suppression:suppression.reasons},companyId,job.id);return}
  const contactRecord=(await db.execute(sql`SELECT id,role,email,phone FROM contacts WHERE company_id=${companyId} AND invalid=false AND verification_status IN ('SYNTAX_VALID','DOMAIN_VALID','MX_VALID','DELIVERY_VALIDATED') ORDER BY CASE role WHEN 'LOGISTICS' THEN 1 WHEN 'OPERATIONS' THEN 2 WHEN 'PURCHASING' THEN 3 WHEN 'SALES' THEN 4 WHEN 'GENERAL' THEN 5 ELSE 6 END,CASE WHEN email IS NOT NULL THEN 0 ELSE 1 END LIMIT 1`)).rows[0] as any;const contact=Boolean(contactRecord);
  const research=(await db.execute(sql`SELECT use_case,refrigeration_fit,transport_fit_signals,recurrence_signals,buying_signals,outsourcing_signals,business_role,transport_demand_role,has_own_fleet,outsources_transport,moves_physical_goods,contact_assessment FROM research_results WHERE company_id=${companyId} ORDER BY created_at DESC LIMIT 1`)).rows[0] as any;const parseSignals=(value:unknown)=>Array.isArray(value)?value.filter(item=>item&&typeof item.evidenceId==='string'&&typeof item.signal==='string'):[];
  const score=scoreCompany({evidence:evidence.map(item=>({id:String(item.id),excerpt:String(item.excerpt),signalType:String(item.signal_type),observedAt:item.observed_at,confidence:Number(item.confidence)})),address:company.address,contact,contactRole:contactRecord?.role,contactKind:contactRecord?.email?'EMAIL':contactRecord?.phone?'PHONE':undefined,research:research?{useCase:research.use_case,refrigerationFit:research.refrigeration_fit,transportFitSignals:parseSignals(research.transport_fit_signals),recurrenceSignals:parseSignals(research.recurrence_signals),buyingSignals:parseSignals(research.buying_signals),outsourcingSignals:parseSignals(research.outsourcing_signals),businessRole:research.business_role,transportDemandRole:research.transport_demand_role,hasOwnFleet:research.has_own_fleet,outsourcesTransport:research.outsources_transport,movesPhysicalGoods:research.moves_physical_goods,contactAssessment:research.contact_assessment}:undefined});
  const decision=classifyScore(score,{AUTO_SEND_THRESHOLD:config.AUTO_SEND_THRESHOLD,REVIEW_THRESHOLD:config.REVIEW_THRESHOLD});const operationFit=score.transportOperationFit??score.fit;const externalDemand=score.externalTransportDemand??score.need;await db.execute(sql`INSERT INTO qualifications(company_id,fit,need,geography,contact_quality,recency,total,transport_need,vehicle_fit,recurrence,transport_fit,transport_operation_fit,external_transport_demand,use_case,refrigeration_fit,confidence,decision,reasoning) VALUES(${companyId},${operationFit},${externalDemand},${score.geography},${score.contactQuality},${score.recency},${score.total},${externalDemand},${legacyVehicleFit(operationFit)},${score.recurrence??0},${score.transportFit??score.total},${operationFit},${externalDemand},${score.useCase??'UNKNOWN'},${score.refrigerationFit??'UNKNOWN'},${score.confidence},${decision},${JSON.stringify(score.reasoning)}::jsonb)`);
  const mode=await effectiveMode(db,config);const next=decision==='DISCARD'?'DISCARDED':mode==='AUTO'&&decision==='AUTO_ELIGIBLE'?'QUALIFIED':'REVIEW';await db.execute(sql`UPDATE companies SET status=CASE WHEN status IN ('BLOCKED','STOPPED') THEN status ELSE ${next} END,updated_at=now() WHERE id=${companyId}`);await audit(db,'QUALIFIED',{decision,total:score.total,breakdown:score,mode},companyId,job.id);if(decision!=='DISCARD')await enqueue(db,'DRAFT',{companyId},new Date(),{idempotencyKey:`DRAFT:${companyId}:DEFAULT_TRANSPORT_OUTREACH`});if(score.total>=config.REVIEW_THRESHOLD&&deps.notifier)await deps.notifier.notify(decision==='AUTO_ELIGIBLE'?'HIGH_SCORE_LEAD':'REVIEW_REQUIRED',`${company.name}: score ${score.total} (${decision})`);
}
