import {sql} from 'drizzle-orm';
import type {Config} from '../../config.js';
import type {Db} from '../../db/client.js';
import {audit} from '../../audit.js';
import {OpenAIResearchProvider,type ResearchProvider,type ResearchResult,validateResearchResult} from '../../qualification/ai-research.js';
import {inferBusinessRole,inferHasOwnFleet,inferRefrigerationFit,inferTransportDemandRole,inferUseCase} from '../../qualification/scorer.js';
import type {JobDependencies} from '../dependencies.js';
import {enqueue} from '../queue.js';

function fallback(input:{company:string;evidence:{id:string;excerpt:string}[]}):ResearchResult{
  const text=input.evidence.map(item=>item.excerpt).join(' ');const lower=text.toLowerCase();const signals=input.evidence.filter(item=>/refriger|congel|distribu|entrega|log[ií]st|mayorista|horeca|repart|transport|fleter/i.test(item.excerpt)).map(item=>({evidenceId:item.id,signal:'observed_transport_signal'}));const coldSignals=input.evidence.filter(item=>/refriger|congel|cadena de fr[ií]o|ultracongel|helad|l[aá]cte/i.test(item.excerpt)).map(item=>({evidenceId:item.id,signal:'observed_refrigeration_signal'}));const useCase=inferUseCase(text);const refrigerationFit=inferRefrigerationFit(text);return{companyType:/distribu|mayorista/i.test(lower)?'DISTRIBUTOR':'UNKNOWN',relevance:signals.length?0.8:0.2,summary:'Clasificacion determinista por evidencia publica persistida.',detectedSignals:signals,reasoningSummary:'No hay credencial de IA configurada; se conservan solo senales observables.',recommendedAction:signals.length?'REVIEW':'DISCARD',confidence:signals.length?'MEDIUM':'LOW',businessModel:/distribu|mayorista/i.test(lower)?'distribution':'unknown',businessRole:inferBusinessRole(text),transportDemandRole:inferTransportDemandRole(text),hasOwnFleet:inferHasOwnFleet(text),outsourcesTransport:'UNKNOWN',outsourcingSignals:[],deliveryOperation:signals.length?'distribution_or_delivery':'unknown',customerType:'unknown',distributionPattern:'unknown',transportOpportunity:0,transportOpportunityReason:'Deterministic fallback; external demand requires review.',regulatoryUncertainties:[],distributionModel:/distribu|entrega|log[ií]st|repart/i.test(lower)?'distribution':'unknown',geography:/caba|gba|gran buenos|am[bm]a|buenos aires/i.test(lower)?'CABA/GBA':'unknown',potentialTransportNeed:signals.length?'possible transport need':'unknown',movesPhysicalGoods:signals.length>0,transportOperation:signals.length?'distribution_or_delivery':'unknown',transportFitSignals:signals,useCase,refrigerationFit,recurrenceSignals:input.evidence.filter(item=>/diari|semanal|recurrent|frecuent|reposici/i.test(item.excerpt)).map(item=>({evidenceId:item.id,signal:'observed_recurrence'})),buyingSignals:input.evidence.filter(item=>/buscamos|contrat|proveedor|terceriz|cotiz|servicio/i.test(item.excerpt)).map(item=>({evidenceId:item.id,signal:'observed_buying_signal'})),contactAssessment:'unknown',evidenceIds:[...new Set([...signals,...coldSignals].map(item=>item.evidenceId))],uncertainties:['AI provider not configured']};
}

export async function researchHandler(db:Db,config:Config,job:any,deps:JobDependencies){
  const companyId=String(job.payload.companyId);const company=(await db.execute(sql`SELECT name FROM companies WHERE id=${companyId}`)).rows[0] as any;if(!company)throw new Error('COMPANY_NOT_FOUND');
  const evidence=(await db.execute(sql`SELECT id,excerpt FROM evidence WHERE company_id=${companyId} ORDER BY observed_at DESC LIMIT 30`)).rows as any[];if(!evidence.length)throw new Error('RESEARCH_REQUIRES_EVIDENCE');
  const sources=(await db.execute(sql`SELECT url,source_type FROM sources WHERE company_id=${companyId} ORDER BY created_at DESC LIMIT 50`)).rows as any[];const contacts=(await db.execute(sql`SELECT email,phone,source_url,verification_status FROM contacts WHERE company_id=${companyId} ORDER BY email NULLS LAST,phone NULLS LAST LIMIT 50`)).rows as any[];const provider:ResearchProvider=deps.research??(config.OPENAI_API_KEY?new OpenAIResearchProvider(config):{research:async(input)=>fallback(input)});const evidenceInput=evidence.map(item=>({id:String(item.id),excerpt:String(item.excerpt)}));
  let result:ResearchResult;try{result=validateResearchResult(await provider.research({company:company.name,sources:sources.map(item=>({url:String(item.url),sourceType:String(item.source_type)})),contacts:contacts.map(item=>({email:item.email??undefined,phone:item.phone??undefined,sourceUrl:item.source_url??undefined,verificationStatus:item.verification_status??undefined})),evidence:evidenceInput}),evidenceInput.map(item=>item.id))}catch(error){if(error instanceof Error&&error.message==='AI_INVALID_EVIDENCE_REFERENCE')await audit(db,'AI_INVALID_EVIDENCE_REFERENCE',{evidenceIds:evidenceInput.map(item=>item.id)},companyId,job.id);throw error}
  const transportFitSignals=result.transportFitSignals??result.detectedSignals??[];const recurrenceSignals=result.recurrenceSignals??[];const buyingSignals=result.buyingSignals??[];const outsourcingSignals=result.outsourcingSignals??[];const evidenceIds=result.evidenceIds??[...new Set([...transportFitSignals,...recurrenceSignals,...buyingSignals,...outsourcingSignals].map(item=>item.evidenceId))];const modelUsed=result.modelUsed??(config.OPENAI_API_KEY?config.OPENAI_MODEL:'deterministic-fallback');const escalated=result.escalated??false;
  await db.execute(sql`INSERT INTO research_results(company_id,model,model_used,escalated,escalation_reason,business_model,business_role,transport_demand_role,has_own_fleet,outsources_transport,outsourcing_signals,delivery_operation,customer_type,distribution_pattern,transport_opportunity,transport_opportunity_reason,regulatory_uncertainties,refrigeration_relevance,distribution_model,geography,potential_transport_need,signals,uncertainties,summary,confidence,usage,moves_physical_goods,transport_operation,transport_fit_signals,use_case,refrigeration_fit,recurrence_signals,buying_signals,contact_assessment,evidence_ids) VALUES(${companyId},${modelUsed},${modelUsed},${escalated},${result.escalationReason??null},${result.businessModel??result.companyType},${result.businessRole??'UNKNOWN'},${result.transportDemandRole??'UNKNOWN'},${result.hasOwnFleet??'UNKNOWN'},${result.outsourcesTransport??'UNKNOWN'},${JSON.stringify(outsourcingSignals)}::jsonb,${result.deliveryOperation??'unknown'},${result.customerType??'unknown'},${result.distributionPattern??'unknown'},${result.transportOpportunity??0},${result.transportOpportunityReason??''},${JSON.stringify(result.regulatoryUncertainties??[])}::jsonb,${Math.round((result.relevance??0)*100)},${result.distributionModel??'unknown'},${result.geography??'unknown'},${result.potentialTransportNeed??'unknown'},${JSON.stringify(result.detectedSignals)}::jsonb,${JSON.stringify(result.uncertainties??[])}::jsonb,${result.summary},${result.confidence==='HIGH'?90:result.confidence==='MEDIUM'?65:35},${result.usage?JSON.stringify(result.usage):null}::jsonb,${result.movesPhysicalGoods===true?true:result.movesPhysicalGoods===false?false:null},${result.transportOperation??'unknown'},${JSON.stringify(transportFitSignals)}::jsonb,${result.useCase??'UNKNOWN'},${result.refrigerationFit??'UNKNOWN'},${JSON.stringify(recurrenceSignals)}::jsonb,${JSON.stringify(buyingSignals)}::jsonb,${result.contactAssessment??'unknown'},${JSON.stringify(evidenceIds)}::jsonb)`);
  await audit(db,'RESEARCH_COMPLETED',{modelUsed,escalated,escalationReason:result.escalationReason??null,evidenceIds,detectedSignals:result.detectedSignals,businessRole:result.businessRole,transportDemandRole:result.transportDemandRole,outsourcingSignals},companyId,job.id);await enqueue(db,'QUALIFY',{companyId},new Date(),{idempotencyKey:`QUALIFY:${companyId}`});
}
