import {describe,expect,it} from 'vitest';
import {validatePreparedMessage} from '../src/outreach/preflight.js';

const clean={companyName:'Empresa',toEmail:'contacto@empresa.com',subject:'Contacto comercial | Distribución y reparto',body:['Hola equipo de Empresa,','','Vi que realizan distribución y reparto para empresas en CABA y GBA.','','Desde R&M hermanos brindamos servicios de distribución y reparto para empresas en CABA y GBA, con una flota de 4 Renault Master.','Podemos asignar una unidad de uso exclusivo para su empresa, de carga seca, refrigerada o congelada, con modalidad permanente o por hora, según la necesidad de la operación.','','Contamos con una unidad con capacidad para transportar productos refrigerados y congelados.','¿Actualmente trabajan con transporte tercerizado o suelen necesitar capacidad adicional para distribución y reparto?','','Consultar disponibilidad: https://wa.me/541160397716','','O simplemente respondan este correo y seguimos por acá.','','Saludos,\nR&M hermanos\nSoluciones que mueven tu empresa\n1160397716\nrymhermanos.logistica@gmail.com\nhttps://rymhermanos.com.ar\nCABA y GBA','','Este mensaje fue enviado porque encontramos información pública de contacto de Empresa y consideramos que nuestros servicios podrían ser relevantes para su operación.','Si prefieren no recibir nuevos mensajes de nuestra parte, respondan indicando "No contactar".'].join('\n')};

describe('outreach preflight',()=>{
  it('accepts the current clean template',()=>expect(validatePreparedMessage(clean)).toEqual([]));
  it('rejects scraped navigation and internal contact evidence',()=>{const issues=validatePreparedMessage({...clean,body:clean.body.replace('Vi que realizan distribución y reparto para empresas en CABA y GBA.','HAGA SU PEDIDO ONLINE Proveedores Nosotros Productos contacto@empresa.com')});expect(issues.some(issue=>issue.includes('HAGA SU PEDIDO'))).toBe(true);expect(issues.some(issue=>issue.includes('Proveedores'))).toBe(true);expect(issues.some(issue=>issue.includes('@[\\w.-]+'))).toBe(true)});
  it('rejects the old sender profile markers',()=>expect(validatePreparedMessage({...clean,body:clean.body.replace('4 Renault Master','Renault Master refrigerada')})).toContain('BAD_BODY:flota de Renault Master refrigerada'));
  it('rejects a navigation label used as the company name',()=>expect(validatePreparedMessage({...clean,companyName:'INICIO'})).toContain('GENERIC_COMPANY_NAME'));
});
