import {describe,expect,it} from 'vitest';
import {DEFAULT_WHATSAPP_URL,renderProspectingEmailHtml,renderProspectingEmailText} from '../src/outreach/templates/prospecting-email.js';

const base={companyName:'Empresa <Prueba>',recipientGreeting:'equipo de Empresa <Prueba>',personalizedEvidence:'Vi que trabajan con distribuci\u00f3n en CABA.',senderName:'R&M hermanos',senderEmail:'rymhermanos.logistica@gmail.com',senderPhone:'1160397716'};

describe('prospecting HTML email template',()=>{
  it('escapes personalized values and uses a text fallback for a missing logo',()=>{const html=renderProspectingEmailHtml(base);expect(html).toContain('Empresa &lt;Prueba&gt;');expect(html).not.toContain('<script');expect(html).toContain('R&amp;M hermanos');expect(html).toContain('Arial,Helvetica,sans-serif')});
  it('renders refrigeration only when explicitly enabled',()=>{expect(renderProspectingEmailHtml(base)).not.toContain('productos refrigerados');expect(renderProspectingEmailHtml({...base,showRefrigerationCapability:true})).toContain('transportar productos refrigerados y congelados')});
  it('validates WhatsApp URL and keeps the CTA explicit',()=>{const html=renderProspectingEmailHtml(base);expect(html).toContain(`href="${DEFAULT_WHATSAPP_URL.replace(/&/g,'&amp;')}"`);expect(html).toContain('Consultar disponibilidad');expect(()=>renderProspectingEmailHtml({...base,whatsappUrl:'javascript:alert(1)'})).toThrow()});
  it('links the sender phone and header to WhatsApp and the website',()=>{const html=renderProspectingEmailHtml(base);expect(html).toContain('>1160397716</a>');expect(html).toContain('<a href="https://rymhermanos.com.ar" target="_blank" style="display:inline-block;color:#08254A;text-decoration:none;"><div');expect(html).toContain('https://rymhermanos.com.ar');expect(html).not.toContain('&#x20;')});
  it('renders equivalent plain text without undefined, forms or tracking pixels',()=>{const text=renderProspectingEmailText({...base,showRefrigerationCapability:true});expect(text).toContain('Vi que trabajan con distribuci\u00f3n en CABA.');expect(text).toContain('transportar productos refrigerados y congelados');expect(text).not.toMatch(/undefined|null|<form|<script|tracking|pixel/i)});
  it('emphasizes an exclusive unit and flexible duration',()=>{const html=renderProspectingEmailHtml(base);const text=renderProspectingEmailText(base);for(const value of ['unidad de uso exclusivo','carga seca','refrigerada','congelada','permanente o por hora','choferes capacitados','recorridos extensos','entregas y cobranzas','tratar directamente con sus clientes','servicio personalizado']){expect(`${html}${text}`).toContain(value)}expect(html).toContain('Unidad exclusiva');expect(html).toContain('Permanente o por hora')});
  it('supports a configured logo URL',()=>{const html=renderProspectingEmailHtml({...base,logoUrl:'https://example.com/logo.png'});expect(html).toContain('src="https://example.com/logo.png"');expect(html).toContain('alt="R&amp;M hermanos"')});
});
