import {describe,expect,it,beforeAll,afterAll,beforeEach} from 'vitest';
import {createDb,closeDb} from '../../src/db/client.js';
import {migrate} from '../../src/db/migrate.js';
import {reserveSendSlots} from '../../src/outreach/reservation.js';
import {replyPollHandler} from '../../src/jobs/handlers/reply-handler.js';
const url=process.env.TEST_DATABASE_URL;const enabled=process.env.RUN_PG_INTEGRATION==='1'&&Boolean(url);const client=enabled?createDb({DATABASE_URL:url!,OUTREACH_MODE:'MANUAL'} as any):undefined;
describe.skipIf(!enabled)('send reservation concurrency',()=>{
  beforeAll(async()=>migrate(client!.pool));beforeEach(async()=>{await client!.pool.query('TRUNCATE companies,messages,outreach_send_reservations CASCADE')});afterAll(async()=>closeDb(client!));
  it('does not reserve the final daily slot twice',async()=>{const company=(await client!.pool.query("INSERT INTO companies(name,normalized_name) VALUES('Race','race') RETURNING id")).rows[0];const messages=(await client!.pool.query("INSERT INTO messages(company_id,direction,body,idempotency_key) VALUES($1,'OUTBOUND','body','race-message-1'),($1,'OUTBOUND','body','race-message-2') RETURNING id",[company.id])).rows;const results=await Promise.allSettled([reserveSendSlots(client!.db,messages[0].id,1,1),reserveSendSlots(client!.db,messages[1].id,1,1)]);expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);expect((await client!.pool.query('SELECT count(*)::int AS n FROM outreach_send_reservations')).rows[0].n).toBe(2)});
  it('reconciles uncertain delivery before any retry',async()=>{const company=(await client!.pool.query("INSERT INTO companies(name,normalized_name) VALUES('Reconcile','reconcile') RETURNING id")).rows[0];const message=(await client!.pool.query("INSERT INTO messages(company_id,direction,body,idempotency_key,outbound_state) VALUES($1,'OUTBOUND','body','stable-key','RECONCILING') RETURNING id",[company.id])).rows[0];const config:any={OUTREACH_MODE:'MANUAL',OPENAI_API_KEY:'',TELEGRAM_BOT_TOKEN:'',DATABASE_URL:'',OUTREACH_ENABLED:false};const gmail={send:async()=>({messageId:'unused'}),listInbox:async()=>[],getMessage:async()=>{throw new Error('unused')},findByIdempotencyKey:async()=>({messageId:'gmail-reconciled',threadId:'thread-reconciled'})};await replyPollHandler(client!.db,config,{id:'reconcile-job',payload:{}},{gmail});expect((await client!.pool.query('SELECT outbound_state,gmail_message_id FROM messages WHERE id=$1',[message.id])).rows[0]).toEqual({outbound_state:'SENT',gmail_message_id:'gmail-reconciled'})});
});
