import 'dotenv/config';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import {sql} from 'drizzle-orm';
import {loadConfig} from '../src/config.js';
import {closeDb,createDb} from '../src/db/client.js';
import {migrate} from '../src/db/migrate.js';
import {classifyPersistedRefrigeration,type RefrigerationSegment} from '../src/qualification/refrigeration.js';

type InventoryRow={companyId:string;companyName:string;domain:string|null;companyStatus:string;email:string;role:string;verificationStatus:string;invalid:boolean;useCase:string|null;refrigerationFit:string|null;qualificationConfidence:string|null;qualificationDecision:string|null;qualificationCreatedAt:string|null;researchUseCase:string|null;researchRefrigerationFit:string|null;suppressed:boolean;segment:RefrigerationSegment;recommendation:string};

function csv(value:unknown){const text=String(value??'');return '"' + text.replace(/"/g,'""') + '"'}
function recommendation(row:{invalid:boolean;suppressed:boolean;segment:RefrigerationSegment;companyStatus:string;verificationStatus:string}){if(row.invalid)return'DO_NOT_SEND_INVALID';if(row.suppressed)return'DO_NOT_SEND_SUPPRESSED';if(['BLOCKED','STOPPED','DISCARDED'].includes(row.companyStatus))return'DO_NOT_SEND_COMPANY_STATUS';if(!['DOMAIN_VALID','MX_VALID','DELIVERY_VALIDATED'].includes(row.verificationStatus))return'HOLD_UNVERIFIED';if(row.segment==='REFRIGERATED')return'SEND_COLD_CHAIN';if(row.segment==='NON_REFRIGERATED')return'SEND_GENERAL';return'HOLD_UNCLASSIFIED'}

const config=loadConfig();
const client=createDb(config);
try{
  await migrate(client.pool);
  const result=await client.db.execute(sql`SELECT c.id AS company_id,c.name AS company_name,c.domain,c.status AS company_status,ct.email,ct.role,ct.verification_status,ct.invalid,q.use_case,q.refrigeration_fit,q.confidence AS qualification_confidence,q.decision AS qualification_decision,q.created_at AS qualification_created_at,r.use_case AS research_use_case,r.refrigeration_fit AS research_refrigeration_fit,EXISTS(SELECT 1 FROM suppressions s WHERE s.company_id=c.id OR lower(s.email)=lower(ct.email) OR (s.domain IS NOT NULL AND c.domain IS NOT NULL AND lower(s.domain)=lower(c.domain))) AS suppressed FROM companies c JOIN contacts ct ON ct.company_id=c.id AND ct.email IS NOT NULL AND btrim(ct.email)<>'' LEFT JOIN LATERAL(SELECT use_case,refrigeration_fit,confidence,decision,created_at FROM qualifications WHERE company_id=c.id ORDER BY created_at DESC LIMIT 1) q ON true LEFT JOIN LATERAL(SELECT use_case,refrigeration_fit FROM research_results WHERE company_id=c.id ORDER BY created_at DESC LIMIT 1) r ON true ORDER BY lower(ct.email),c.name`);
  const rows=(result.rows as any[]).map(row=>{const segment=classifyPersistedRefrigeration({useCase:row.use_case,refrigerationFit:row.refrigeration_fit,fallbackUseCase:row.research_use_case,fallbackRefrigerationFit:row.research_refrigeration_fit});return{companyId:String(row.company_id),companyName:String(row.company_name),domain:row.domain??null,companyStatus:String(row.company_status),email:String(row.email),role:String(row.role),verificationStatus:String(row.verification_status),invalid:Boolean(row.invalid),useCase:row.use_case??null,refrigerationFit:row.refrigeration_fit??null,qualificationConfidence:row.qualification_confidence??null,qualificationDecision:row.qualification_decision??null,qualificationCreatedAt:row.qualification_created_at?new Date(row.qualification_created_at).toISOString():null,researchUseCase:row.research_use_case??null,researchRefrigerationFit:row.research_refrigeration_fit??null,suppressed:Boolean(row.suppressed),segment,recommendation:recommendation({invalid:Boolean(row.invalid),suppressed:Boolean(row.suppressed),segment,companyStatus:String(row.company_status),verificationStatus:String(row.verification_status)})} as InventoryRow});
  const counts=rows.reduce<Record<string,number>>((acc,row)=>{acc[row.segment]=(acc[row.segment]??0)+1;acc[row.recommendation]=(acc[row.recommendation]??0)+1;return acc},{});
  const timestamp=new Date().toISOString().replace(/[:.]/g,'-');const directory=path.resolve('reports');await fs.mkdir(directory,{recursive:true});const jsonPath=path.join(directory,`email-inventory-${timestamp}.json`);const csvPath=path.join(directory,`email-inventory-${timestamp}.csv`);const headers=['companyId','companyName','domain','companyStatus','email','role','verificationStatus','invalid','useCase','refrigerationFit','qualificationConfidence','qualificationDecision','qualificationCreatedAt','researchUseCase','researchRefrigerationFit','suppressed','segment','recommendation'];await fs.writeFile(jsonPath,JSON.stringify({generatedAt:new Date().toISOString(),total:rows.length,counts,rows},null,2),'utf8');await fs.writeFile(csvPath,[headers.join(','),...rows.map(row=>headers.map(header=>csv(row[header as keyof InventoryRow])).join(','))].join('\n'),'utf8');console.log(JSON.stringify({total:rows.length,counts,json:jsonPath,csv:csvPath},null,2));
}catch(error){console.error(`EMAIL_INVENTORY_FAILED: ${error instanceof Error?error.message:String(error)}`);process.exitCode=1}finally{await closeDb(client)}
