import {sql} from 'drizzle-orm';
import type {Db} from '../db/client.js';
import {classifyPersistedRefrigeration,type RefrigerationSegment} from '../qualification/refrigeration.js';

export type OutreachCandidate={companyId:string;companyName:string;companyStatus:string;email:string;verificationStatus:string;invalid:boolean;suppressed:boolean;segment:RefrigerationSegment};

export async function loadOutreachCandidates(db:Db):Promise<OutreachCandidate[]>{
  const result=await db.execute(sql`SELECT c.id AS company_id,c.name AS company_name,c.status AS company_status,ct.email,ct.verification_status,ct.invalid,q.use_case,q.refrigeration_fit,r.use_case AS research_use_case,r.refrigeration_fit AS research_refrigeration_fit,EXISTS(SELECT 1 FROM suppressions s WHERE s.company_id=c.id OR lower(s.email)=lower(ct.email) OR (s.domain IS NOT NULL AND c.domain IS NOT NULL AND lower(s.domain)=lower(c.domain))) AS suppressed FROM companies c JOIN LATERAL(SELECT email,verification_status,invalid FROM contacts WHERE company_id=c.id AND email IS NOT NULL ORDER BY CASE WHEN invalid=false AND verification_status IN ('SYNTAX_VALID','DOMAIN_VALID','MX_VALID','DELIVERY_VALIDATED') THEN 0 ELSE 1 END,(verification_status='DELIVERY_VALIDATED') DESC,(verification_status='MX_VALID') DESC LIMIT 1) ct ON true LEFT JOIN LATERAL(SELECT use_case,refrigeration_fit FROM qualifications WHERE company_id=c.id ORDER BY created_at DESC LIMIT 1) q ON true LEFT JOIN LATERAL(SELECT use_case,refrigeration_fit FROM research_results WHERE company_id=c.id ORDER BY created_at DESC LIMIT 1) r ON true ORDER BY lower(ct.email),c.name`);
  return (result.rows as any[]).map(row=>({companyId:String(row.company_id),companyName:String(row.company_name),companyStatus:String(row.company_status),email:String(row.email),verificationStatus:String(row.verification_status),invalid:Boolean(row.invalid),suppressed:Boolean(row.suppressed),segment:classifyPersistedRefrigeration({useCase:row.use_case,refrigerationFit:row.refrigeration_fit,fallbackUseCase:row.research_use_case,fallbackRefrigerationFit:row.research_refrigeration_fit})}));
}

export function eligibleForOutreach(candidate:OutreachCandidate){return !candidate.invalid&&!candidate.suppressed&&!['BLOCKED','STOPPED','DISCARDED'].includes(candidate.companyStatus)&&['SYNTAX_VALID','DOMAIN_VALID','MX_VALID','DELIVERY_VALIDATED'].includes(candidate.verificationStatus)&&candidate.segment!=='UNKNOWN'}
